config/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# Django locals
from apps.accounts import views as accounts_views
from apps.boards import views 

urlpatterns = [

    # Boards
    # url(r'^$', views.home, name='home'), # replace by bellow using GCBV
    url(r'^$', views.BoardListView.as_view(), name='home'),
    # url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics'),
    # url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.topic_posts, name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='edit_post'),

    # Singup, Login, Logout
    url(r'^signup/$', accounts_views.signup, name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    
    # Password reset & Password reset done
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='registration/password_reset.html',
            email_template_name='accounts/registration/password_reset_email.html',
            subject_template_name='accounts/registration/password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/registration/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/registration/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/registration/password_reset_complete.html'),
        name='password_reset_complete'),

    url(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='accounts/registration/password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/registration/password_change_done.html'),
        name='password_change_done'),

    # Admin dashboard
    path('admin/', admin.site.urls),
]

apps/boards/models.py
# apps/boards/models.py

# Django modules
import math
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import Truncator
from django.utils.html import mark_safe
from markdown import markdown

# Create your models here.

# Board model
class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

# Topic model
class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topics')
    views = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 2
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 2

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)

    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:5]


# Post model
class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

apps/boards/forms.py
# apps/boards/forms.py

# Django modules
from django import forms

# Django locals
from apps.boards.models import Topic, Post

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Topic
        fields = ['subject', 'message'] # message is new field added

"""
This is our first form. It’s a ModelForm associated 
with the Topic model. The subject in the fields list 
inside the Meta class is referring to the subject 
field in the Topic class. 

Now observe that we are defining an extra field named message. 
This refers to the message in the Post we want to save.
"""        

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['message', ]

apps/boards/views.py
# apps/boards/views.py

# Django modules
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.db.models import Count
from django.views.generic import UpdateView, ListView
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Django locals
from apps.boards.forms import NewTopicForm, PostForm
from apps.boards.models import Board, Topic, Post

# Create your views here.

# # Home view 1
# def home(request):
#     boards = Board.objects.all()
#     context = {'boards': boards}
#     return render(request, 'boards/home.html', context )


# Home view 2 using GCBV
class BoardListView(ListView):
    model = Board
    context_object_name = 'boards'
    template_name = 'boards/home.html'


# # BoardTopic view
# def board_topics(request, pk):
#     board = Board.objects.get(pk=pk)
#     context = {'board': board}
#     return render(request, 'topics.html')

# -- replace by the codes bellow

# # BoardTopic view
# def board_topics(request, pk):
#     try:
#         board = Board.objects.get(pk=pk)
#     except Board.DoesNotExist:
#         raise Http404    
#     context = {'board': board}
#     return render(request, 'boards/topics.html', context)

# -- replace by the codes bellow

# # BoardTopic view 1
# def board_topics(request, pk):
#     board = get_object_or_404(Board, pk=pk) # <--- same result
#     context = {'board': board}
#     return render(request, 'boards/topics.html', context)


# # BoardTopic view 2
# def board_topics(request, pk):
#     board = get_object_or_404(Board, pk=pk)
#     topics = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
#     return render(request, 'boards/topics.html', {'board': board, 'topics': topics})


# # BoardTopic view 3 add Pagination
# def board_topics(request, pk):
#     board = get_object_or_404(Board, pk=pk)
#     queryset = board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
#     page = request.GET.get('page', 1)

#     paginator = Paginator(queryset, 10)

#     try:
#         topics = paginator.page(page)
#     except PageNotAnInteger:
#         # fallback to the first page
#         topics = paginator.page(1)
#     except EmptyPage:
#         # probably the user tried to add a page number
#         # in the url, so we fallback to the last page
#         topics = paginator.page(paginator.num_pages)

#     return render(request, 'boards/topics.html', {'board': board, 'topics': topics})


# BoardTopic view 4 add Pagination (GCBV: TopicListView)
class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'boards/topics.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset



# # NewTopic view
# def new_topic(request, pk):
#     board = get_object_or_404(Board, pk=pk)
#     context = {'board':board}
#     return render(request, 'boards/new_topic.html', context)

# -- replace by the codes bellow


# # NewTopic view
# def new_topic(request, pk):
#     board = get_object_or_404(Board, pk=pk)

#     if request.method == 'POST':
#         subject = request.POST['subject']
#         message = request.POST['message']

#         user = User.objects.first()  # TODO: get the currently logged in user

#         topic = Topic.objects.create(
#             subject=subject,
#             board=board,
#             starter=user
#         )

#         post = Post.objects.create(
#             message=message,
#             topic=topic,
#             created_by=user
#         )

#         return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page
#     context = {'board':board}
#     return render(request, 'boards/new_topic.html', context)

# -- replace by the codes bellow


# # NewTopic view
# @login_required
# def new_topic(request, pk):
#     board = get_object_or_404(Board, pk=pk)
#     user = User.objects.first()  # TODO: get the currently logged in user
    
#     if request.method == 'POST':
#         form = NewTopicForm(request.POST)
        
#         if form.is_valid():
#             topic = form.save(commit=False)
#             topic.board = board
#             topic.starter = user
#             topic.save()
#             post = Post.objects.create(
#                 message=form.cleaned_data.get('message'),
#                 topic=topic,
#                 created_by=user
#             )

#             return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page
    
#     else:
#         form = NewTopicForm()

#     context = {'board':board, 'form':form}
#     return render(request, 'boards/new_topic.html', context)  

"""
First we check if the request is a POST or a GET. If the request came 
from a POST, it means the user is submitting some data to the server. 
So we instantiate a form instance passing the POST data to 
the form: form = NewTopicForm(request.POST).
Then, we ask Django to verify the data, check if the form is valid 
if we can save it in the database: if form.is_valid():. If the form 
was valid, we proceed to save the data in the database using form.save(). 
The save() method returns an instance of the Model saved into the database. 
So, since this is a Topic form, it will return the Topic that
was created: topic = form.save(). After that, the common path 
is to redirect the user somewhere else, both to avoid the user 
re-submitting the form by pressing F5 and also to keep the flow 
of the application.
Now, if the data was invalid, Django will add a list of errors to the form. 
After that, the view does nothing and returns in the last 
statement: return render(request, 'new_topic.html', {'form': form}). 
That means we have to update the new_topic.html to display errors properly.
If the request was a GET, we just initialize a new and empty 
form using form = NewTopicForm().

Then, we ask Django to verify the data, check if the form is valid if we 
can save it in the database: if form.is_valid():. If the form was valid, 
we proceed to save the data in the database using form.save(). The save()
method returns an instance of the Model saved into the database. 
So, since this is a Topic form, it will return the Topic that was 
created: topic = form.save(). After that, the common path is to redirect 
the user somewhere else, both to avoid the user re-submitting the form 
by pressing F5 and also to keep the flow of the application.

Now, if the data was invalid, Django will add a list of errors to the form. 
After that, the view does nothing and returns in the last 
statement: return render(request, 'new_topic.html', {'form': form}). 
That means we have to update the new_topic.html to display errors properly.

If the request was a GET, we just initialize a new and 
empty form using form = NewTopicForm().

"""

# -- replace by the codes bellow

# NewTopic view
@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        form = NewTopicForm(request.POST)

        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            # return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page
            return redirect('topic_posts', pk=pk, topic_pk=topic.pk)  # <- here    
    else:
        form = NewTopicForm()

    return render(request, 'boards/new_topic.html', {'board': board, 'form': form})


"""
Note with this codes:
1. New user: Victor
2. Victor logged in
3. He made a topic on Python
4. His topic and his name (as starter) appear on Python topic
5. Similarly if he made something on Django topic,
   the same thing happen
6. See bellow
================================================================================

Boards / Python

-----------
|New topic|
-----------

Topic                   Starter     Replies     Views   Last Update
--------------------------------------------------------------------------------
Victor proposal         Victor      0           0       July 3, 2021, 9:35 a.m.
Python is great         ing         0           0       July 3, 2021, 9:42 a.m.

================================================================================

Boards / Django

-----------
|New topic|
-----------

Topic                   Starter     Replies     Views   Last Update
--------------------------------------------------------------------------------
Hallo every one         ing         0           0       July 3, 2021, 1:07 a.m.
After protecting view   ing         0           0       July 3, 2021, 9:33 a.m.
Victor on Django        Victor      0           0       July 3, 2021, 9:36 a.m.   
================================================================================
"""


# # TopicPosts view 1
# def topic_posts(request, pk, topic_pk):
#     topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
#     return render(request, 'boards/topic_posts.html', {'topic': topic})

# # http://127.0.0.1:8000/boards/1/topics/1/

# # Boards /Django / Hallo every one


# TopicPosts view 2
def topic_posts(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    topic.views += 1
    topic.save()

apps/boards/templates/boards/includes/form.html
<!-- apps/boards/templates/includes/form.html -->

{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

<!--  
<form method="post" novalidate>
   <input type="hidden" name="csrfmiddlewaretoken" value="VTm0XwVwvc6wG8735slKeiccnArr99hHtogRb1x9TCFIdYdPiy78VXQmjMcCHcYm">
   <div class="form-group">
      <label for="id_subject">Subject:</label>
      <input type="text" name="subject" maxlength="255" class="form-control is-invalid" required id="id_subject">
      <div class="invalid-feedback">
         This field is required.
      </div>
   </div>
   <div class="form-group">
      <label for="id_message">Message:</label>
      <textarea name="message" cols="40" rows="5" placeholder="What is on your mind?" maxlength="4000" class="form-control is-invalid" required id="id_message">
</textarea>
      <div class="invalid-feedback">
         This field is required.
      </div>
      <small class="form-text text-muted">
      The max length of the text is 4000.
      </small>
   </div>
   <button type="submit" class="btn btn-success">Post</button>
</form>
-->

<!--

The Django Forms API does much more than processing and validating the data. It also generates the HTML for us.

The form have three rendering options: form.as_table, form.as_ul, and form.as_p. It’s a quick way to render all the fields of a form. As the name suggests, the as_table uses table tags to format the inputs, the as_ul creates an HTML list of inputs, etc.

-->

apps/boards/templates/boards/includes/pagination.html
<!-- apps/boards/templates/includes/pagination.html -->

<!-- {% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}  -->

        <!-- """
        
        ABOVE CODE GIVES PAGINATION BELLOW
        
        <Previous 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,2n Next>
        
        BELLOW CODE GIVES PAGINATION BELLOW
        
        <First | Previous | 40, 50, 61 |Next | Last>

        """   -->   

{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.number > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">First</span>
        </li>
      {% endif %}

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}

      {% if page_obj.number != paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Last</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}